// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profiles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProfile = `-- name: CreateProfile :one
INSERT INTO public.profiles (id, email, display_name, avatar_url)
VALUES ($1, $2, $3, $4)
RETURNING id, email, display_name, avatar_url, created_at, updated_at
`

type CreateProfileParams struct {
	ID          pgtype.UUID
	Email       pgtype.Text
	DisplayName pgtype.Text
	AvatarUrl   pgtype.Text
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, createProfile,
		arg.ID,
		arg.Email,
		arg.DisplayName,
		arg.AvatarUrl,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfileByID = `-- name: GetProfileByID :one
SELECT id, email, display_name, avatar_url, created_at, updated_at
FROM public.profiles
WHERE id = $1
`

func (q *Queries) GetProfileByID(ctx context.Context, id pgtype.UUID) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfileByID, id)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE public.profiles
SET
    display_name = COALESCE($1, display_name),
    avatar_url = COALESCE($2, avatar_url),
    updated_at = NOW()
WHERE id = $3
RETURNING id, email, display_name, avatar_url, created_at, updated_at
`

type UpdateProfileParams struct {
	DisplayName pgtype.Text
	AvatarUrl   pgtype.Text
	ID          pgtype.UUID
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, updateProfile, arg.DisplayName, arg.AvatarUrl, arg.ID)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
